version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - flux-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - flux-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - flux-net

networks:
  flux-net:
    driver: bridge
